version: "3"

services:
  drupal:
    image: adoah/aidockerfiles:php7.2-fpm-dev
    container_name: drupal
    restart: unless-stopped
    volumes:
      - ./drupal-src:/app
    working_dir: /app

  webserver:
    image: nginx:alpine
    container_name: webserver
    environment:
      VIRTUAL_HOST: site.local
      VIRTUAL_PORT: 80
      NGINX_PORT: 80
      NGINX_HOST: site.local
    expose:
      - "80"
    restart: unless-stopped
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./drupal-src/web:/var/www/html

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=site2.local

networks:
  default:
    external:
      name: nginx-proxy
